sudo: required

services:
  - docker

before_install:
  - docker build -t c-wilk/docker-react -f Dockerfile.dev .

script:
  - docker run c-wilk/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react-test-1"
  env: "DockerReactTest1-env"
  bucket_name: "elasticbeanstalk-us-west-2-624885417651"
  bucket_path: "docker-react-test-1"
  on:
    branch: master
  access_key_id: $AWS_USER_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"